### ISSUE TITLE
ok3 feature

### ISSUE THREAD

**Issue by petar** [gov4git/sample-project#14]

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 18:07:14 UTC` by Gov4Git `dev`

#### Notice `m7qoek`
Started managing this issue as Gov4Git concern `14` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `355mod`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `kllioy`
The set of eligible proposals claiming this issue is empty.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 18:16:25 UTC` by Gov4Git `dev`

#### Notice `hw2k6h`
This issue's __priority score__ is now `3.162278`.
The __cost of priority__ is `10.000000`.
The __projected bounty__ is now `10.000000`.

#### Notice `5l6xi2`
The set of eligible proposals claiming this issue is empty.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 18:19:32 UTC` by Gov4Git `dev`

#### Notice `f4hbnr`
This issue was referenced by https://github.com/gov4git/sample-project/pull/13, managed as Gov4Git proposal `13`.

#### Notice `xqf6u5`
This issue, managed as Gov4Git proposal `14`, has been closed 🎉

The issue priority tally was `3.162278`.

Ths issue was resolved by [PR #13](https://github.com/gov4git/sample-project/pull/13):

Tally breakdown by user:
- User @petar contributed `3.162278` votes


#### Notice `hqsnkf`
Gov4Git closed this issue, as the corresponding governance motion `14` has now been closed.
