### ISSUE TITLE
test issue with waimea

### ISSUE THREAD

**Issue by petar** [gov4git/sample-project#15]
description

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 22-Feb-24 17:10:22 UTC` by Gov4Git `dev`

#### Notice `x6oqdv`
Started managing this issue as Gov4Git concern `15` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `2xmh44`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `gc2aty`
The set of eligible proposals claiming this issue is empty.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 22-Feb-24 17:19:42 UTC` by Gov4Git `dev`

#### Notice `eqvsxk`
This issue was referenced by https://github.com/gov4git/sample-project/pull/18, managed as Gov4Git proposal `18`.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 22-Feb-24 17:22:58 UTC` by Gov4Git `dev`

#### Notice `scusrr`
This issue's __priority score__ is now `4.472136`.
The __cost of priority__ is `20.000000`.
The __projected bounty__ is now `8.944272`.

#### Notice `l3nu6d`
The set of eligible proposals claiming this issue is empty.


#### Notice `x74p56`
This issue's __priority score__ is now `4.472136`.
The __cost of priority__ is `20.000000`.
The __projected bounty__ is now `8.944272`.

#### Notice `ypuvxp`
The set of eligible proposals claiming this issue changed:
- https://github.com/gov4git/sample-project/pull/18, managed as Gov4Git proposal `18` with approval score of `3.162278`


#### Notice `rct7lj`
Freezing ❄️ this issue as there are eligible PRs addressing it:
- https://github.com/gov4git/sample-project/pull/18

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Thursday, 22-Feb-24 17:26:06 UTC` by Gov4Git `dev`

#### Notice `rrbx57`
This issue, managed as Gov4Git concern `15`, has been closed 🎉

The __priority score__ of the issue was `4.472136`.

The __cost of priority__ of the issue was `20.000000`.

Ths issue was resolved by [PR #18](https://github.com/gov4git/sample-project/pull/18):

Refunds issued:
- Prioritizer @petar was refunded `20.000000` credits

Issue priority tally by prioritizer was:
- Prioritizer @petar contributed `4.472136` votes


#### Notice `7qsrlh`
Gov4Git closed this issue, as the corresponding governance motion `15` has now been closed.
