### ISSUE TITLE
feature idea

### ISSUE THREAD

**Issue by petar** [gov4git/sample-project#8]
do some stuff

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 05-Feb-24 17:54:31 UTC` by Gov4Git `dev`

#### Notice `oljtzs`
Started managing this issue as Gov4Git concern `8` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `uskutg`
This PR's __projected bounty__ is now `0.000000`.

#### Notice `uss75e`
This PR's __projected bounty__ is now `0.000000`.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 05-Feb-24 20:30:03 UTC` by Gov4Git `dev`

#### Notice `wuijhu`
Started managing this issue as Gov4Git concern `8` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `hwtdt2`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `qxtzpx`
The set of eligible proposals claiming this issue is empty.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 05-Feb-24 20:31:16 UTC` by Gov4Git `dev`

#### Notice `z7rlnm`
This issue's __priority score__ is now `10.000000`.
The __cost of priority__ is `10.000000`.
The __projected bounty__ is now `10.000000`.

#### Notice `2smgcl`
The set of eligible proposals claiming this issue is empty.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 05-Feb-24 20:36:44 UTC` by Gov4Git `dev`

#### Notice `gayimr`
This issue was referenced by https://github.com/gov4git/sample-project/pull/10, managed as Gov4Git proposal `10`.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 00:53:56 UTC` by Gov4Git `dev`

#### Notice `ae6s6a`
Started managing this issue as Gov4Git concern `8` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `l3psxr`
This issue was referenced by https://github.com/gov4git/sample-project/pull/10, managed as Gov4Git proposal `10`.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 01:00:40 UTC` by Gov4Git `dev`

#### Notice `e2m3ta`
This issue's __priority score__ is now `10.000000`.
The __cost of priority__ is `10.000000`.
The __projected bounty__ is now `10.000000`.

#### Notice `7za2hd`
The set of eligible proposals claiming this issue is empty.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 17:23:21 UTC` by Gov4Git `dev`

#### Notice `prpp35`
Started managing this issue as Gov4Git concern `8` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `jicccg`
This issue was referenced by https://github.com/gov4git/sample-project/pull/10, managed as Gov4Git proposal `10`.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 17:28:04 UTC` by Gov4Git `dev`

#### Notice `2ihzpj`
This issue's __priority score__ is now `10.000000`.
The __cost of priority__ is `10.000000`.
The __projected bounty__ is now `10.000000`.

#### Notice `w3qpus`
The set of eligible proposals claiming this issue changed:
- https://github.com/gov4git/sample-project/pull/10, managed as Gov4Git motion `10` with community attention of `0.000000`


#### Notice `n2jddq`
Freezing ❄️ this issue as there are eligible PRs addressing it:
- https://github.com/gov4git/sample-project/pull/10

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Tuesday, 06-Feb-24 17:30:43 UTC` by Gov4Git `dev`

#### Notice `5ficl5`
This issue, managed as Gov4Git proposal `8`, has been closed 🎉

The issue priority tally was `3.162278`.

Ths issue was resolved by [PR #10](https://github.com/gov4git/sample-project/pull/10):

Tally breakdown by user:
- User @petar contributed `3.162278` votes


#### Notice `nhzd4i`
Gov4Git closed this issue, as the corresponding governance motion `8` has now been closed.
